name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build android application
      run: ./gradlew build
    - name: upload android app
      uses: actions/upload-artifact@v3.0.0
      with:
      # Artifact name
        name: upload andriod apk
        path: ./app/app-dev-debug.apk
  
